# Generated by Django 4.2.9 on 2026-02-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tùy chỉnh')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá')),
                ('category', models.CharField(choices=[('sugar', 'Đường'), ('ice', 'Đá'), ('topping', 'Topping'), ('other', 'Khác')], default='other', max_length=50, verbose_name='Loại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Tùy chỉnh',
                'verbose_name_plural': 'Tùy chỉnh',
                'db_table': 'customizations',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price_small', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá size S')),
                ('price_medium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá size M')),
                ('price_large', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá size L')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_small', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Khối lượng size S')),
                ('quantity_medium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Khối lượng size M')),
                ('quantity_large', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Khối lượng size L')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='ingredients.ingredient', verbose_name='Nguyên liệu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Công thức',
                'verbose_name_plural': 'Công thức',
                'db_table': 'recipes',
                'unique_together': {('product', 'ingredient')},
            },
        ),
    ]
