# Generated by Django 4.2.9 on 2026-02-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhân viên')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('manager', 'Quản lý'), ('cashier', 'Thu ngân'), ('barista', 'Pha chế'), ('server', 'Phục vụ')], max_length=50, verbose_name='Vai trò')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lương')),
                ('hire_date', models.DateField(verbose_name='Ngày vào làm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Ngày làm việc')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Số giờ làm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='staff.staff', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Chấm công',
                'db_table': 'work_logs',
                'ordering': ['-work_date'],
                'unique_together': {('staff', 'work_date')},
            },
        ),
    ]
