# Generated by Django 4.2.26 on 2026-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('manager', 'Quản lý'), ('cashier', 'Thu ngân'), ('barista', 'Barista'), ('parttime', 'Part-time')], max_length=50, verbose_name='Vai trò'),
        ),
    ]
