# Generated by Django 4.2.26 on 2026-05-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Ngày làm việc')),
                ('shift', models.CharField(choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều'), ('evening', 'Ca tối')], max_length=20, verbose_name='Ca làm')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Số giờ dự kiến')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lương theo giờ')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='staff.staff', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Phân công ca',
                'verbose_name_plural': 'Phân công ca',
                'db_table': 'staff_shift_assignments',
                'ordering': ['-work_date', 'shift', 'staff__name'],
                'unique_together': {('staff', 'work_date', 'shift')},
            },
        ),
    ]
