# Generated by Codex on 2026-05-03

from datetime import time

from django.db import migrations, models


def seed_shift_rules(apps, schema_editor):
    ShiftRule = apps.get_model('staff', 'ShiftRule')
    defaults = [
        ('morning', time(7, 0), time(12, 0), 2, 4, 1),
        ('afternoon', time(13, 0), time(18, 0), 2, 4, 2),
        ('evening', time(18, 0), time(22, 0), 1, 3, 3),
    ]
    for shift, start_time, end_time, min_staff, max_staff, sort_order in defaults:
        ShiftRule.objects.get_or_create(
            shift=shift,
            defaults={
                'start_time': start_time,
                'end_time': end_time,
                'min_staff': min_staff,
                'max_staff': max_staff,
                'sort_order': sort_order,
                'is_active': True,
            },
        )


def unseed_shift_rules(apps, schema_editor):
    ShiftRule = apps.get_model('staff', 'ShiftRule')
    ShiftRule.objects.filter(shift__in=['morning', 'afternoon', 'evening']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('staff', '0004_shiftassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'shift',
                    models.CharField(
                        choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều'), ('evening', 'Ca tối')],
                        max_length=20,
                        unique=True,
                        verbose_name='Ca',
                    ),
                ),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('min_staff', models.PositiveSmallIntegerField(default=2, verbose_name='Tối thiểu nhân sự')),
                ('max_staff', models.PositiveSmallIntegerField(default=4, verbose_name='Tối đa nhân sự')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
            ],
            options={
                'verbose_name': 'Cấu hình ca',
                'verbose_name_plural': 'Cấu hình ca',
                'db_table': 'staff_shift_rules',
                'ordering': ['sort_order', 'shift'],
            },
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['work_date', 'shift'], name='staff_shift_work_da_56037a_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['staff', 'work_date'], name='staff_shift_staff_i_9c1ef4_idx'),
        ),
        migrations.RunPython(seed_shift_rules, reverse_code=unseed_shift_rules),
    ]
