# Generated by Django 4.2.26 on 2026-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_points_earned_order_points_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('preparing', 'Đang chế biến'), ('completed', 'Hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('N/A', 'Không size')], max_length=10, verbose_name='Size'),
        ),
    ]
