# Generated by Django 4.2.9 on 2026-02-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('points', models.IntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('tier', models.CharField(choices=[('Đồng', 'Đồng'), ('Bạc', 'Bạc'), ('Vàng', 'Vàng'), ('Kim cương', 'Kim cương')], default='Đồng', max_length=20, verbose_name='Hạng thành viên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'db_table': 'customers',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10, verbose_name='Size')),
                ('customizations', models.JSONField(blank=True, null=True, verbose_name='Tùy chỉnh (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_drinks', to='customers.customer', verbose_name='Khách hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Đồ uống yêu thích',
                'verbose_name_plural': 'Đồ uống yêu thích',
                'db_table': 'favorite_drinks',
                'ordering': ['-created_at'],
            },
        ),
    ]
