# Generated by Django 4.2.9 on 2026-02-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nguyên liệu')),
                ('unit', models.CharField(max_length=20, verbose_name='Đơn vị (g, ml, cái)')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số lượng hiện tại')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số lượng tối thiểu')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá/đơn vị')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhà cung cấp')),
                ('last_restock_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhập gần nhất')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
    ]
