# Generated by Django 4.2.26 on 2026-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Ki-lo-gam (kg)'), ('g', 'Gam (g)'), ('l', 'Lít (l)'), ('ml', 'Mili-lít (ml)'), ('pcs', 'Cái/Chiếc (pcs)')], default='kg', max_length=20, verbose_name='Đơn vị'),
        ),
    ]
