# Generated by Django 4.2.9 on 2026-02-10 15:59

from django.db import migrations, models  # type: ignore[import]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(unique=True, verbose_name='Ngày')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Doanh thu')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Số đơn hàng')),
                ('total_customers', models.IntegerField(default=0, verbose_name='Số khách hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Thống kê ngày',
                'verbose_name_plural': 'Thống kê ngày',
                'db_table': 'daily_stats',
                'ordering': ['-stat_date'],
            },
        ),
    ]
